export const cvData = {
  profile: {
    name: 'Jérémie Lucotte',
    title: 'Full-Stack Developer',
    location: 'Paris, France',
    summary:
      `Full-Stack Developer with 5+ years of experience in blockchain and startup environments.Experienced in building scalable, production-ready applications across frontend and backend systems. Hackathon winner with a strong focus on system architecture, performance, and emerging technologies including AI, robotics, and crypto.`,
  },
  contact: {
    email: 'contact@jeremielucotte.com',
    github: 'github.com/Chinoiserie1',
    linkedin: 'linkedin.com/in/jeremielucotte',
    twitter: 'twitter.com/chixxdev',
  },
  skills: [
    { category: 'Blockchain', items: ['Solidity', 'Rust', 'Hardhat', 'Foundry'] },
    { category: 'Frontend', items: ['React', 'Next.js', 'React Native', 'Expo', 'TypeScript', 'Tailwind CSS'] },
    { category: 'Backend', items: ['Node.js', 'Express', 'Nest.js', 'Fastify', 'Python', 'Rust', 'PostgreSQL', 'Prisma'] },
    { category: 'DevOps', items: ['Docker', 'Git', 'Vercel', 'Railway', 'PostHog'] },
  ],
  projects: [
    {
      name: 'EECI-IGSC ',
      description: 'Website for European Embedded Control Institute with course management and registration systems.',
      role: 'Full-stack Developer',
      tech: ['Next.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Stripe'],
      features: ['Module catalog and registration system', 'Stripe payment integration', 'Back-office web app for admin to manage modules and students', 'email using resend', 'Analytics using matomo'],
      status: 'live',
      url: 'eeci-igsc.eu',
    },
    {
      name: 'Repliq',
      description: 'Mobile app that let you share your portfolio and earn with it.',
      role: 'Full-stack Developer',
      tech: ['React Native', 'Expo', 'TypeScript', 'Nativewind CSS', 'PostgreSQL', 'Prisma', 'Stripe'],
      features: ['Portfolio sharing and monetization', 'Privy authentication', 'websocket for real-time updates', 'Notification'],
      status: 'live',
      url: 'https://x.com/repliq_xyz',
    },
    {
      name: 'Trenches',
      description: 'Crypto reputation tokenization platform. RADAR Colosseum hackathon winner.',
      role: 'Full-stack Developer',
      tech: ['Rust', 'Express.js', 'prisma', 'Next.js', 'PostgreSQL'],
      features: ['Bonding curve for reputation tokens', 'On-chain performance tracking', 'Copy trading mechanism'],
      status: 'archived',
    },
    {
      name: 'Cushion',
      description: 'DeFi vault implementing CPPI strategy. Max TVL 250k USD.',
      role: 'Full-stack Developer',
      tech: ['Express.js', 'prisma', 'Next.js', 'Python', 'PostgreSQL'],
      features: ['CPPI strategy implementation', 'Automated rebalancing'],
      status: 'archived',
    },
    {
      name: 'Metahood',
      description: 'NFT marketplace for metaverse real estate and virtual assets.',
      role: 'Blockchain Developer',
      tech: ['Solidity'],
      features: ['Listing and selling NFTs', 'Auction sales'],
      status: 'archived',
    },
    {
      name: 'Undoxxed Book',
      description: 'Minting website for Undoxxed Book collection with waitlist management and minting phases. + ERC721 smart contract on Ethereum mainnet, audited by Opengem.',
      role: 'Full-stack Developer',
      tech: ['Solidity', 'Foundry', 'Ethereum', 'Next.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Tailwind CSS'],
      features: ['Gas-optimized minting', 'Merkle tree whitelist verification', 'Arweave & IPFS storage', 'Audited by Opengem'],
      status: 'live',
      url: 'mint.undoxxedbook.com',
    },
    {
      name: 'Eteos',
      description: 'Real-world asset tokenization with UUPS proxy and on-chain metadata.',
      role: 'Lead Blockchain Developer',
      tech: ['Solidity', 'Polygon', 'Foundry'],
      features: ['UUPS upgradeable proxy pattern', 'On-chain metadata'],
      status: 'archived',
    },
  ],
}
